import { useEffect, useMemo, useState } from 'react';
import { Search, MapPin, Wind, Droplets, CloudRain, Eye, AlertTriangle, Activity, BarChart3, Map as MapIcon, ShieldAlert, CloudSun, ThermometerSun, RefreshCw, LocateFixed, Gauge, Sunrise, Sunset, Database, ExternalLink, Upload, Link2, CheckCircle2, XCircle, HelpCircle, Crosshair } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, BarChart, Bar, CartesianGrid, AreaChart, Area } from 'recharts';
import { MapContainer, TileLayer, CircleMarker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { geocode, getWeather, getAlerts, getHistorical, getMapPoints, getHealth, verifyPost } from './services/api';

const codeText={0:'Clear sky',1:'Mainly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy rain showers',95:'Thunderstorm',96:'Thunderstorm with hail',99:'Thunderstorm with heavy hail'};
const iconFor=c=>c===0||c===1?'☀️':c===2?'⛅':c===3?'☁️':c>=95?'⛈️':c>=51?'🌧️':'🌫️';
const fmtTime=x=>x?new Date(x).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';

function App(){
 const [page,setPage]=useState('Dashboard'),[query,setQuery]=useState('');
 const [place,setPlace]=useState({name:'Visakhapatnam',latitude:17.6868,longitude:83.2185,country:'India'});
 const [w,setW]=useState(null),[alerts,setAlerts]=useState([]),[official,setOfficial]=useState(null),[history,setHistory]=useState(null),[mapPoints,setMapPoints]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[health,setHealth]=useState(null),[lastUpdated,setLastUpdated]=useState(null);
 const demoWeather=()=>({current:{time:new Date().toISOString(),temperature_2m:28,apparent_temperature:30,relative_humidity_2m:72,wind_speed_10m:14,wind_gusts_10m:24,precipitation:0,cloud_cover:18,surface_pressure:1011,weather_code:1},hourly:{time:Array.from({length:24},(_,i)=>new Date(Date.now()+i*3600000).toISOString()),temperature_2m:Array.from({length:24},(_,i)=>25+Math.round(5*Math.sin(i/24*Math.PI*2))),precipitation_probability:Array.from({length:24},(_,i)=>i>9&&i<15?25:10),wind_speed_10m:Array.from({length:24},(_,i)=>12+(i%5)),relative_humidity_2m:Array.from({length:24},(_,i)=>68+(i%8))},daily:{time:Array.from({length:7},(_,i)=>new Date(Date.now()+i*86400000).toISOString().slice(0,10)),weather_code:[1,2,61,3,80,1,0],temperature_2m_max:[31,30,28,29,29,32,33],temperature_2m_min:[24,23,23,24,24,25,25],precipitation_probability_max:[10,20,70,20,60,10,5],wind_speed_10m_max:[18,20,25,18,28,16,15],uv_index_max:[7,7,6,7,6,8,9],sunrise:Array(7).fill(new Date().toISOString()),sunset:Array(7).fill(new Date(Date.now()+12*3600000).toISOString())}});
 const demoHistory=()=>({daily:{time:Array.from({length:30},(_,i)=>new Date(Date.now()-(29-i)*86400000).toISOString().slice(0,10)),temperature_2m_max:Array.from({length:30},(_,i)=>29+Math.round(3*Math.sin(i/5))),temperature_2m_min:Array.from({length:30},(_,i)=>23+Math.round(2*Math.sin(i/4))),precipitation_sum:Array.from({length:30},(_,i)=>i%7===0?22:(i%4===0?5:0))}});
 const demoPoints=p=>[-1,0,1].flatMap(a=>[-1,0,1].map(b=>({lat:p.latitude+a*.45,lon:p.longitude+b*.45,temp:25+Math.round(Math.random()*8),wind:10+Math.round(Math.random()*15),rain:Math.round(Math.random()*8),humidity:60+Math.round(Math.random()*25),code:1})));
 const load=async p=>{setLoading(true);setError('');const results=await Promise.allSettled([getWeather(p.latitude,p.longitude),getAlerts(p.latitude,p.longitude),getHistorical(p.latitude,p.longitude),getMapPoints(p.latitude,p.longitude),getHealth()]);const [weatherR,alertR,histR,mapR,healthR]=results;const liveWeather=weatherR.status==='fulfilled'?weatherR.value:demoWeather();setW(liveWeather);setAlerts(alertR.status==='fulfilled'?(alertR.value.alerts||[]):[]);setOfficial(alertR.status==='fulfilled'?alertR.value.official:null);setHistory(histR.status==='fulfilled'?histR.value:demoHistory());setMapPoints(mapR.status==='fulfilled'?(mapR.value.points||[]):demoPoints());setHealth(healthR.status==='fulfilled'?healthR.value:{ok:false,demo:true});if(results.some(r=>r.status==='rejected'))setError('Some live sources are unavailable. Showing safe demo/fallback data where needed.');setLastUpdated(new Date());setLoading(false)};
 useEffect(()=>{load(place)},[]);
 const search=async e=>{e.preventDefault();if(!query.trim())return;try{setLoading(true);const d=await geocode(query);if(!d.results?.length)throw new Error('Location not found');const r=d.results[0];const p={name:r.name,latitude:r.latitude,longitude:r.longitude,country:r.country||'',admin1:r.admin1||''};setPlace(p);setQuery('');await load(p)}catch(e){setError(e.message);setLoading(false)}};
 const locate=()=>navigator.geolocation?.getCurrentPosition(async pos=>{const p={name:'My Location',latitude:pos.coords.latitude,longitude:pos.coords.longitude,country:''};setPlace(p);await load(p)},()=>setError('Location permission was not available.'));
 const hourly=useMemo(()=>w?.hourly?.time?.slice(0,24).map((t,i)=>({time:new Date(t).toLocaleTimeString([],{hour:'2-digit'}),temp:Math.round(w.hourly.temperature_2m[i]),rain:w.hourly.precipitation_probability?.[i]??0,wind:Math.round(w.hourly.wind_speed_10m[i]),humidity:w.hourly.relative_humidity_2m?.[i]??0,code:w.hourly.weather_code?.[i]??0}))||[],[w]);
 const days=useMemo(()=>w?.daily?.time?.map((d,i)=>({day:i===0?'Today':new Date(d).toLocaleDateString([],{weekday:'short'}),icon:iconFor(w.daily.weather_code[i]),high:Math.round(w.daily.temperature_2m_max[i]),low:Math.round(w.daily.temperature_2m_min[i]),rain:w.daily.precipitation_probability_max?.[i]??0,wind:Math.round(w.daily.wind_speed_10m_max?.[i]??0),uv:Math.round(w.daily.uv_index_max?.[i]??0)}))||[],[w]);
 return <div className="app"><div className="orb a"/><div className="orb b"/>
 <header className="nav"><div className="brand"><div className="brandIcon"><CloudSun/></div><div><b>WeatherIQ</b><small>National Weather Big Data Analytics</small></div></div><nav>{[['Dashboard',Activity],['Forecast',CloudSun],['Analytics',BarChart3],['Live Map',MapIcon],['Disaster',ShieldAlert],['Verify Report',Crosshair]].map(([n,I])=><button type="button" className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={16}/>{n}</button>)}</nav><div className="live"><i/> LIVE</div></header>
 <main><section className="hero"><div><label>REAL-TIME WEATHER INTELLIGENCE</label><h1>Understand the sky.<br/><em>Predict what's next.</em></h1><p>Live observations, forecasts, historical analytics, risk intelligence and social-report verification in one platform.</p></div><div className="heroBadge"><Database/><span>DATA PIPELINE<strong>{health?.ok?'ONLINE':'CONNECTING'}</strong></span></div></section>
 {page!=='Verify Report'&&<form className="search" onSubmit={search}><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search city, district or location..."/></div><button type="button" onClick={locate}><LocateFixed/> My Location</button><button type="button" className="refresh" onClick={()=>load(place)}><RefreshCw className={loading?'spin':''}/></button></form>}
 {error&&<div className="error">⚠ {error}</div>}
 {page==='Dashboard'&&<Dashboard c={w?.current} place={place} hourly={hourly} days={days} alerts={alerts} loading={loading} daily={w?.daily}/>} 
 {page==='Forecast'&&<Forecast days={days} hourly={hourly}/>} 
 {page==='Analytics'&&<Analytics hourly={hourly} history={history}/>} 
 {page==='Live Map'&&<LiveMap place={place} points={mapPoints}/>} 
 {page==='Disaster'&&<Disaster alerts={alerts} official={official} c={w?.current} place={place} hourly={hourly}/>} 
 {page==='Verify Report'&&<VerifyReport/>}
 </main><footer><span>WeatherIQ • Open-Meteo + IMD data</span><span>Last sync: {lastUpdated?.toLocaleTimeString()||'—'} • Verification is evidence-based, not proof</span></footer></div>
}
function Dashboard({c,place,hourly,days,alerts,loading,daily}){if(loading&&!c)return <Loader/>;return <><section className="grid2"><div className="card current"><div className="label">CURRENT CONDITIONS <span>LIVE</span></div><div className="currentRow"><div className="bigIcon">{iconFor(c?.weather_code)}</div><div><div className="temp">{Math.round(c?.temperature_2m)}<sup>°C</sup></div><h2>{place.name}</h2><p>{codeText[c?.weather_code]||'Weather'} • Feels like {Math.round(c?.apparent_temperature)}°C</p></div></div><div className="stats"><Stat I={ThermometerSun} n="Temperature" v={`${Math.round(c?.temperature_2m)}°C`}/><Stat I={Droplets} n="Humidity" v={`${c?.relative_humidity_2m}%`}/><Stat I={Wind} n="Wind" v={`${Math.round(c?.wind_speed_10m)} km/h`}/></div></div><div className="card conditions"><div className="title"><h2>Atmospheric Conditions</h2><span>{fmtTime(c?.time)}</span></div><div className="conditionGrid"><Stat I={CloudRain} n="Precipitation" v={`${c?.precipitation??0} mm`}/><Stat I={Eye} n="Cloud Cover" v={`${c?.cloud_cover??0}%`}/><Stat I={Gauge} n="Pressure" v={`${Math.round(c?.surface_pressure??0)} hPa`}/><Stat I={Wind} n="Wind Gusts" v={`${Math.round(c?.wind_gusts_10m??0)} km/h`}/></div><div className="sun"><span><Sunrise/> {fmtTime(daily?.sunrise?.[0])}</span><span><Sunset/> {fmtTime(daily?.sunset?.[0])}</span></div></div></section><ChartCard data={hourly} title="24-HOUR TEMPERATURE" dataKey="temp" unit="°C"/><Forecast days={days}/><Alerts alerts={alerts}/></>}
function Stat({I,n,v}){return <div className="stat"><I/><span>{n}</span><strong>{v}</strong></div>}
function ChartCard({data,title,dataKey,unit=''}){return <section className="card chart"><div className="title"><div><label>{title}</label><h2>{dataKey==='temp'?'Temperature Trend':dataKey==='rain'?'Precipitation Probability':'Wind Trend'}</h2></div><span>LIVE</span></div><ResponsiveContainer width="100%" height={270}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.08}/><XAxis dataKey="time"/><YAxis/><Tooltip formatter={v=>[`${v}${unit}`,dataKey]}/><Line type="monotone" dataKey={dataKey} strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></section>}
function Forecast({days = [], hourly = []}){return <section><div className="sectionTitle"><label>EXTENDED OUTLOOK</label><h2>7-Day Forecast</h2></div><div className="forecast">{(days.length?days:[{day:'No data',icon:'—',high:'—',low:'—',rain:0,wind:0,uv:0}]).map(d=><div className="card day" key={d.day}><span>{d.day}</span><b>{d.icon}</b><strong>{d.high}° <small>{d.low}°</small></strong><i>{d.rain}% rain</i><em>💨 {d.wind} km/h • UV {d.uv}</em></div>)}</div>{hourly.length>0&&<ChartCard data={hourly} title="HOURLY PRECIPITATION PROBABILITY" dataKey="rain" unit="%"/>}</section>}
function Analytics({hourly,history}){const hist=history?.daily?.time?.map((d,i)=>({date:new Date(d).toLocaleDateString([],{month:'short',day:'numeric'}),max:Math.round(history.daily.temperature_2m_max[i]),min:Math.round(history.daily.temperature_2m_min[i]),rain:Number(history.daily.precipitation_sum[i]||0)}))||[];return <section><div className="sectionTitle"><label>WEATHER ANALYTICS</label><h2>Atmospheric Trends</h2></div><div className="analyticsGrid"><ChartCard data={hourly} title="TEMPERATURE" dataKey="temp" unit="°C"/><ChartCard data={hourly} title="WIND SPEED" dataKey="wind" unit=" km/h"/></div><section className="card chart"><div className="title"><div><label>30-DAY HISTORY</label><h2>Historical Temperature Range</h2></div><span>ARCHIVE</span></div><ResponsiveContainer width="100%" height={290}><AreaChart data={hist}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.08}/><XAxis dataKey="date"/><YAxis/><Tooltip/><Area type="monotone" dataKey="max" fillOpacity={.18} strokeWidth={2}/><Area type="monotone" dataKey="min" fillOpacity={.08} strokeWidth={2}/></AreaChart></ResponsiveContainer></section><section className="card chart"><label>30-DAY RAINFALL</label><ResponsiveContainer width="100%" height={250}><BarChart data={hist}><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="rain"/></BarChart></ResponsiveContainer></section></section>}
function LiveMap({place,points}){return <section><div className="sectionTitle"><label>LIVE WEATHER MAP</label><h2>Regional Conditions</h2></div><div className="mapWrap"><MapContainer center={[place.latitude,place.longitude]} zoom={8} scrollWheelZoom><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{points.map((p,i)=><CircleMarker center={[p.lat,p.lon]} radius={12} key={i}><Popup><b>{Math.round(p.temp)}°C</b><br/>Wind {Math.round(p.wind)} km/h<br/>Humidity {p.humidity}%<br/>Rain {p.rain} mm</Popup></CircleMarker>)}</MapContainer></div></section>}

const disasterHistory = [
 {id:'cyclone',title:'Cyclones',icon:'🌀',summary:'Coastal cyclone history for the selected area, ordered by year.',events:[
   {year:'2021',date:'Sep 2021',name:'Cyclone Gulab',location:'Andhra Pradesh–Odisha coast',metric:'Landfall: 26 Sep',label:'Severe cyclonic storm',impact:'Heavy rain, strong winds and coastal disruption in Andhra Pradesh.',source:'IMD RSMC cyclone reports'},
   {year:'2022',date:'May 2022',name:'Cyclone Asani',location:'Andhra Pradesh coast',metric:'Landfall influence',label:'Cyclonic storm',impact:'Heavy rain and strong winds affected coastal Andhra Pradesh.',source:'IMD RSMC cyclone reports'},
   {year:'2023',date:'Dec 2023',name:'Cyclone Michaung',location:'Andhra Pradesh coast / Bay of Bengal',metric:'6–19 Dec',label:'Severe cyclonic storm',impact:'Heavy rainfall and flooding impacts were reported across the region.',source:'IMD Annual Report 2023'},
   {year:'2024',date:'Nov–Dec 2024',name:'Cyclone Fengal',location:'South Bay of Bengal / Andhra coast influence',metric:'23 Nov–2 Dec',label:'Cyclonic storm',impact:'Heavy rainfall and coastal weather impacts across southern/eastern India.',source:'IMD RSMC 2024 archive'},
   {year:'2025',date:'Oct 2025',name:'Cyclone Montha',location:'Andhra Pradesh–Odisha coast',metric:'25–29 Oct',label:'Severe cyclonic storm',impact:'A major Bay of Bengal system affecting the east coast.',source:'IMD RSMC 2025 archive'}
 ]},
 {id:'flood',title:'Floods & Heavy Rain',icon:'🌊',summary:'Five-year rainfall and flood timeline for the selected area/region.',events:[
   {year:'2021',date:'Sep 2021',name:'Gulab-associated heavy rain',location:'Coastal Andhra Pradesh',metric:'Extreme rainfall',label:'Cyclone-linked rain',impact:'Short-duration intense rainfall and local flooding risk.',source:'IMD cyclone and rainfall monitoring'},
   {year:'2022',date:'Oct–Nov 2022',name:'Northeast monsoon heavy rain',location:'Andhra Pradesh',metric:'Heavy rain episodes',label:'Monsoon event',impact:'Urban and low-lying areas faced waterlogging/flood risk during intense spells.',source:'IMD rainfall monitoring'},
   {year:'2023',date:'Dec 2023',name:'Michaung rainfall/flooding',location:'Coastal Andhra Pradesh',metric:'Very heavy rain',label:'Cyclone-linked',impact:'Flooding and transport disruption followed intense rainfall.',source:'IMD Annual Report 2023'},
   {year:'2024',date:'Aug–Sep 2024',name:'Monsoon heavy-rain episodes',location:'Andhra Pradesh',metric:'Heavy rainfall',label:'Monsoon event',impact:'Local flooding and drainage stress occurred during intense rain spells.',source:'IMD Annual Climate Summary 2024'},
   {year:'2025',date:'Monsoon 2025',name:'Heavy-rain / flood episodes',location:'South Peninsular India',metric:'110% of LPA',label:'Above-normal annual rainfall nationally',impact:'Multiple extreme-rainfall and flood events were documented by IMD.',source:'IMD Annual Report 2025'}
 ]},
 {id:'heatwave',title:'Heat Waves',icon:'🔥',summary:'Five-year heat-risk timeline and extreme-temperature context.',events:[
   {year:'2021',date:'Apr–Jun 2021',name:'Pre-monsoon heat episodes',location:'India / selected region',metric:'Heat stress',label:'Seasonal risk',impact:'Hot and humid conditions can elevate heat-index risk.',source:'IMD climate monitoring'},
   {year:'2022',date:'Mar–May 2022',name:'Early heat-wave season',location:'India',metric:'Multiple heat-wave spells',label:'Pre-monsoon',impact:'Several parts of India experienced heat-wave conditions.',source:'IMD Annual Report 2022'},
   {year:'2023',date:'Mar–Jun 2023',name:'Heat Wave',location:'India',metric:'119',label:'Reported deaths',impact:'IMD recorded reported heat-wave fatalities during 2023.',source:'IMD Annual Report 2023'},
   {year:'2024',date:'Apr–Jun 2024',name:'Major heat-wave season',location:'East, northwest, north & central India',metric:'+0.65°C',label:'Annual mean anomaly',impact:'2024 was the warmest year in India since nationwide records began in 1901.',source:'IMD Annual Climate Summary 2024'},
   {year:'2025',date:'2025',name:'Extreme-weather heat events',location:'India',metric:'>2690',label:'Deaths from extreme weather events',impact:'IMD reported widespread extreme weather including heat waves.',source:'IMD Annual Report 2025'}
 ]},
 {id:'thunderstorm',title:'Thunderstorms & Lightning',icon:'⚡',summary:'Five-year lightning and thunderstorm impact timeline.',events:[
   {year:'2021',date:'2021',name:'Lightning / thunderstorm season',location:'India',metric:'Seasonal events',label:'High-frequency hazard',impact:'Lightning remains a recurring severe-weather hazard in pre-monsoon and monsoon periods.',source:'IMD extreme-weather monitoring'},
   {year:'2022',date:'Mar–May 2022',name:'Pre-monsoon lightning',location:'Andhra Pradesh & India',metric:'3',label:'Reported lightning deaths in Andhra Pradesh',impact:'IMD recorded lightning fatalities in Andhra Pradesh during the season.',source:'IMD Annual Report 2022'},
   {year:'2023',date:'2023',name:'Lightning',location:'India',metric:'692',label:'Reported deaths',impact:'Lightning caused the largest reported number of deaths among listed 2023 extreme events.',source:'IMD Annual Report 2023'},
   {year:'2024',date:'2024',name:'Lightning & thunderstorms',location:'India',metric:'Extreme events',label:'Recurring hazard',impact:'Lightning and thunderstorms remained among the nationally reported extreme weather hazards.',source:'IMD Annual Climate Summary 2024'},
   {year:'2025',date:'2025',name:'Lightning / thunderstorm impacts',location:'India',metric:'>1300',label:'Deaths from lightning + thunderstorm',impact:'IMD reported more than 1300 deaths from lightning and thunderstorm among 2025 extreme events.',source:'IMD Annual Report 2025'}
 ]},
 {id:'landslide',title:'Landslides',icon:'⛰️',summary:'Rainfall-triggered landslide history and risk signals.',events:[
   {year:'2021',date:'2021 monsoon',name:'Monsoon slope instability',location:'India',metric:'Rain-triggered',label:'Primary trigger',impact:'Saturated slopes can fail after prolonged or intense rainfall.',source:'IMD / NDMA hazard guidance'},
   {year:'2022',date:'2022 monsoon',name:'Heavy-rain landslide risk',location:'India',metric:'Rain + terrain',label:'Risk signal',impact:'Intense rainfall increases slope-failure potential in hilly areas.',source:'IMD Annual Report 2022'},
   {year:'2023',date:'Jun 2023',name:'Chamoli snow avalanche',location:'Uttarakhand',metric:'1',label:'Reported death',impact:'Extreme terrain hazards included avalanche and rain-triggered slope risks.',source:'IMD Annual Report 2023'},
   {year:'2024',date:'2024 monsoon',name:'Landslide events',location:'India',metric:'Rainfall + terrain',label:'Risk signal',impact:'Extreme rainfall and saturated slopes increased local landslide risk.',source:'IMD Annual Climate Summary 2024'},
   {year:'2025',date:'2025',name:'Landslide / heavy-rain events',location:'India',metric:'Extreme rainfall',label:'Recurring hazard',impact:'IMD included landslides among major extreme-weather impacts in 2025.',source:'IMD Annual Report 2025'}
 ]},
 {id:'drought',title:'Drought',icon:'🏜️',summary:'Five-year drought and rainfall-anomaly context.',events:[
   {year:'2021',date:'2021',name:'Rainfall anomaly monitoring',location:'India',metric:'Seasonal anomaly',label:'Water-stress indicator',impact:'Drought risk is assessed from rainfall deficits, soil moisture and water availability.',source:'IMD climate monitoring'},
   {year:'2022',date:'2022',name:'Seasonal rainfall variability',location:'India',metric:'Regional deficit/excess',label:'Climate signal',impact:'Regional rainfall anomalies can create agricultural and water-resource stress.',source:'IMD Annual Report 2022'},
   {year:'2023',date:'2023',name:'Rainfall variability',location:'India',metric:'Regional anomaly',label:'Drought indicator',impact:'IMD rainfall monitoring tracks departures from climatological normal.',source:'IMD Annual Report 2023'},
   {year:'2024',date:'2024',name:'Rainfall anomaly year',location:'India',metric:'104% of LPA',label:'Annual rainfall',impact:'National rainfall was above long-period average, but regional deficits still occurred.',source:'IMD Annual Climate Summary 2024'},
   {year:'2025',date:'2025',name:'Above-normal rainfall year',location:'India',metric:'110% of LPA',label:'Annual rainfall',impact:'National rainfall was above normal while some regions remained below normal.',source:'IMD Annual Report 2025'}
 ]},
 {id:'wildfire',title:'Forest Fires',icon:'🔥',summary:'Five-year fire-risk timeline using heat, dryness and wind signals.',events:[
   {year:'2021',date:'2021 dry season',name:'Forest-fire risk season',location:'India',metric:'Heat + dryness',label:'Risk drivers',impact:'Dry vegetation and wind can accelerate fire spread.',source:'NDMA / official hazard framework'},
   {year:'2022',date:'2022 dry season',name:'Forest-fire risk',location:'India',metric:'Heat + dryness',label:'Risk drivers',impact:'High temperatures and dry fuels increase ignition and spread potential.',source:'NDMA / IMD hazard framework'},
   {year:'2023',date:'2023 dry season',name:'Fire-risk conditions',location:'India',metric:'Heat + wind',label:'Risk drivers',impact:'Weather conditions can increase forest-fire spread risk.',source:'NDMA multi-hazard framework'},
   {year:'2024',date:'2024 dry season',name:'Fire-risk monitoring',location:'India',metric:'Heat + dryness + wind',label:'Risk drivers',impact:'Weather-linked fire risk requires local fire and official warnings.',source:'NDMA / official warning systems'},
   {year:'2025',date:'2025',name:'Extreme heat / fire-weather context',location:'India',metric:'Extreme weather',label:'Risk drivers',impact:'Heat, dryness and wind remain important fire-spread indicators.',source:'IMD Annual Report 2025'}
 ]}
];

function disasterProbability(id,hourly,c,alerts=[]){
 const h=hourly||[]; const temps=h.map(x=>Number(x.temp)||0), rains=h.map(x=>Number(x.rain)||0), winds=h.map(x=>Number(x.wind)||0);
 const maxT=Math.max(Number(c?.temperature_2m)||0,...temps), maxRain=Math.max(Number(c?.precipitation)||0,...rains), maxWind=Math.max(Number(c?.wind_gusts_10m)||0,...winds);
 const thunder=h.filter(x=>[95,96,99].includes(x.code)).length;
 const danger=alerts.some(a=>a.level==='danger'), warning=alerts.some(a=>a.level==='warning');
 let p=0,reason='Low atmospheric trigger signal';
 if(id==='cyclone'){p=Math.min(95,Math.round((maxWind>=70?55:maxWind>=50?30:maxWind>=35?12:3)+(danger?25:warning?10:0)));reason=maxWind>=50?'Strong-wind signal in the next 24h':'No strong-wind/cyclone-level signal in the next 24h';}
 if(id==='flood'){p=Math.min(95,Math.round(Math.max(maxRain*0.65, rains.filter(x=>x>=50).length*10)+(danger?20:warning?8:0)));reason=maxRain>=50?'Heavy-rain probability is elevated':'Rainfall probability is currently limited';}
 if(id==='heatwave'){p=Math.min(95,Math.round(maxT>=42?80:maxT>=40?55:maxT>=38?28:maxT>=35?10:2));reason=maxT>=40?'Extreme heat signal detected':'Temperatures are below the high-risk heat threshold';}
 if(id==='thunderstorm'){p=Math.min(95,Math.round(thunder*18 + (maxRain>=40?15:0) + (danger?15:warning?7:0)));reason=thunder?'Thunderstorm weather codes appear in the next 24h':'No thunderstorm weather code in the next 24h';}
 if(id==='landslide'){p=Math.min(90,Math.round(maxRain*0.55 + (maxRain>=60?15:0)));reason=maxRain>=50?'Heavy rain can increase slope-instability risk':'Rainfall trigger is currently limited';}
 if(id==='drought'){p=Math.max(0,Math.round(maxRain<10?18:5));reason=maxRain<10?'Dry 24-hour outlook; drought is a longer-term hazard':'Near-term rainfall reduces immediate drought signal';}
 if(id==='wildfire'){p=Math.min(90,Math.round((maxT>=38?35:maxT>=35?18:5)+(maxWind>=30?20:0)+(maxRain<10?20:0)));reason=maxT>=38&&maxRain<10?'Hot and dry conditions can increase fire spread risk':'Weather conditions do not strongly favor rapid fire spread';}
 return {p,reason};
}

function DisasterHistoryCard({item, selected, onClick, probability}){
 return <button type="button" className={`disasterCard ${selected?'selected':''}`} onClick={onClick}>
   <span className="disasterEmoji">{item.icon}</span><div><b>{item.title}</b><small>{item.summary}</small><strong className="probBadge">Next 24h: {probability}%</strong></div><span className="openMark">{selected?'−':'+'}</span>
 </button>
}
function DisasterHistoryDetail({item,probability}){
 const chartData=item.events.map(e=>({year:e.year,value:typeof e.metric==='number'?e.metric:(e.metric.match(/\d+/)?.[0]||0)}));
 return <section className="card disasterDetail">
   <div className="title"><div><label>5-YEAR AREA TIMELINE • 2021–2025</label><h2>{item.icon} {item.title}</h2></div><span>24H RISK {probability}%</span></div>
   <div className="probPanel"><div><b>{probability}%</b><span>estimated probability in next 24 hours</span></div><div className="probTrack"><i style={{width:`${probability}%`}}/></div><small>Estimate from the next-24-hour weather forecast and threshold signals. It is not an official disaster probability.</small></div>
   <div className="historyEvents">{item.events.slice().sort((a,b)=>Number(a.year)-Number(b.year)).map((e,i)=><div className="historyEvent" key={i}><div className="eventYear">{e.year}</div><div><b>{e.name}</b><span>{e.date} • {e.location}</span><p><strong>{e.metric}</strong> — {e.label}. {e.impact}.</p><small>Source: {e.source}</small></div></div>)}</div>
   <div className="historyChart"><ResponsiveContainer width="100%" height={210}><BarChart data={chartData}><XAxis dataKey="year"/><YAxis/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer></div>
   <div className="historyNote">Timeline is sorted oldest → newest and is scoped to the selected location/region where the curated record supports it. Official warnings take priority for emergency decisions.</div>
 </section>
}

function Disaster({alerts,official,c,place,hourly}){
 const [selected,setSelected]=useState('cyclone');
 const item=disasterHistory.find(x=>x.id===selected)||disasterHistory[0];
 const probabilities=Object.fromEntries(disasterHistory.map(x=>[x.id,disasterProbability(x.id,hourly,c,alerts)]));
 const selectedRisk=probabilities[selected]?.p||0;
 return <section><div className="sectionTitle"><label>DISASTER & SAFETY CENTER</label><h2>Risk Intelligence</h2><p className="verifyIntro">Every card shows a 5-year timeline (2021–2025) and an estimated next-24-hour probability based on the selected area's forecast signals.</p></div>
 <div className="riskHero card"><ShieldAlert/><div><b>{alerts.some(a=>a.level==='danger')?'ACTION REQUIRED':alerts.some(a=>a.level==='warning')?'WEATHER ADVISORY':'NO THRESHOLD-BASED SEVERE RISK'}</b><p>{place.name} • {Math.round(c?.temperature_2m??0)}°C • Wind {Math.round(c?.wind_speed_10m??0)} km/h</p></div></div>
 <div className="disasterCards">{disasterHistory.map(x=><DisasterHistoryCard item={x} probability={probabilities[x.id].p} selected={selected===x.id} onClick={()=>setSelected(x.id)} key={x.id}/>)}</div>
 <DisasterHistoryDetail item={item} probability={selectedRisk}/>
 <Alerts alerts={alerts}/>
 <section className="card official"><div className="title"><div><label>OFFICIAL FEED</label><h2>India Meteorological Department</h2></div><span>{official?.available?'CONNECTED':'UNAVAILABLE'}</span></div>{official?.items?.length?official.items.slice(0,5).map((x,i)=><div className="officialItem" key={i}><AlertTriangle/><div><b>{x.title}</b><p>{x.description?.replace(/<[^>]*>/g,'').slice(0,260)||'IMD bulletin'}</p></div>{x.link&&<a href={x.link} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a>}</div>):<p className="muted">The official IMD feed could not be reached. The local threshold engine remains available as an analytics aid.</p>}</section>
 <div className="card notice"><AlertTriangle/> <div><b>Safety note</b><p>This platform is an analytics layer, not an emergency-warning authority. For life-safety decisions, follow official government and local disaster-management alerts.</p></div></div></section>}

function Alerts({alerts=[]}){return <section className="alerts"><div className="sectionTitle"><label>ALERT MONITOR</label><h2>Weather Alerts</h2></div>{alerts.map((a,i)=><div className={`alert ${a.level}`} key={i}><AlertTriangle/><div><b>{a.title}</b><p>{a.message}</p></div></div>)}</section>}
function VerifyReport(){
 const [url,setUrl]=useState(''),[text,setText]=useState(''),[location,setLocation]=useState(''),[eventTime,setEventTime]=useState(''),[file,setFile]=useState(null),[gps,setGps]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const readImage=async f=>{setFile(f);setGps(null);if(!f)return;try{const exifr=await import('exifr');const data=await exifr.gps(f);if(data?.latitude&&data?.longitude)setGps({latitude:data.latitude,longitude:data.longitude,source:'image EXIF'});}catch(e){}};
 const run=async e=>{e.preventDefault();if(!url.trim()){setMsg('Paste the public post URL first.');return}setBusy(true);setMsg('');setResult(null);try{const r=await verifyPost({url,text,location,eventTime,imageGps:gps});setResult(r)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const verdict=result?.verdict;
 return <section className="verifyPage"><div className="sectionTitle"><label>SOCIAL DISASTER REPORT VERIFICATION</label><h2>Can this event be corroborated?</h2><p className="verifyIntro">Paste a public social-media post URL. WeatherIQ extracts available post metadata, coordinates or location clues, checks the weather around that location, and compares the claim with official warning feeds. It reports evidence strength—not a guaranteed truth judgment.</p></div><div className="verifyGrid"><form className="card verifyForm" onSubmit={run}><div className="verifyStep"><span>01</span><div><b>Post URL</b><p>Use a publicly accessible post or article URL.</p></div></div><div className="urlInput"><Link2/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></div><div className="verifyStep"><span>02</span><div><b>Claim details</b><p>Optional context makes location and event classification stronger.</p></div></div><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Claimed location (e.g. Visakhapatnam)"/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste the caption/claim, e.g. 'flash flooding in...'" rows="4"/><input type="datetime-local" value={eventTime} onChange={e=>setEventTime(e.target.value)}/><div className="upload"><Upload/><input type="file" accept="image/*" onChange={e=>readImage(e.target.files?.[0])}/><span>{gps?`GPS found: ${gps.latitude.toFixed(5)}, ${gps.longitude.toFixed(5)}`:'Optional image: GPS EXIF can improve location verification'}</span></div>{msg&&<div className="error">⚠ {msg}</div>}<button className="verifyBtn" disabled={busy}>{busy?<><RefreshCw className="spin"/> Verifying evidence...</>:<><Crosshair/> Verify Event</>}</button></form><div className="card verifyInfo"><div className="verifyIcon"><Crosshair/></div><h3>Verification pipeline</h3><ol><li><b>Extract</b><span>Public page metadata, title, description, image URL and coordinates when exposed.</span></li><li><b>Locate</b><span>Resolve coordinates or a named location to a geographic point.</span></li><li><b>Corroborate</b><span>Compare weather conditions and forecast signals with the claimed event.</span></li><li><b>Cross-check</b><span>Look for matching official IMD warning language.</span></li></ol><div className="verifyLegend"><span><CheckCircle2/> Corroborated</span><span><XCircle/> Not corroborated</span><span><HelpCircle/> Insufficient evidence</span></div></div></div>{result&&<VerificationResult result={result}/>}</section>
}
function VerificationResult({result}){const cls=result.verdict==='corroborated'?'good':result.verdict==='not-corroborated'?'bad':'unknown';return <section className="card result"><div className={`verdict ${cls}`}>{result.verdict==='corroborated'?<CheckCircle2/>:result.verdict==='not-corroborated'?<XCircle/>:<HelpCircle/>}<div><label>VERIFICATION RESULT</label><h2>{result.verdict==='corroborated'?'CORROBORATED':result.verdict==='not-corroborated'?'NOT CORROBORATED':'INSUFFICIENT EVIDENCE'}</h2><p>Evidence score: {result.score ?? 0}%</p></div></div><div className="resultGrid"><div><label>DETECTED EVENT</label><strong>{result.tags?.length?result.tags.join(' • '):'No disaster type confidently detected'}</strong></div><div><label>RESOLVED LOCATION</label><strong>{result.location?`${result.location.name} (${Number(result.location.latitude).toFixed(4)}, ${Number(result.location.longitude).toFixed(4)})`:'Location unresolved'}</strong></div></div>{result.post?.title&&<div className="postMeta"><b>{result.post.title}</b><p>{result.post.description||'No public description available.'}</p></div>}<div className="evidence"><label>EVIDENCE</label>{result.evidence?.map((x,i)=><div key={i}><CheckCircle2/>{x}</div>)}</div>{result.official?.items?.length>0&&<div className="officialMini"><label>OFFICIAL FEED SIGNALS</label>{result.official.items.slice(0,4).map((x,i)=><div key={i}><AlertTriangle/>{x.title}</div>)}</div>}<div className="limitations"><b>Important limitations</b>{result.limitations?.map((x,i)=><p key={i}>• {x}</p>)}</div></section>}
function Loader(){return <div className="loader"><RefreshCw className="spin"/> Loading live weather data...</div>}
export default App;
